// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"fmt"
	"os"
	"log"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

// LoadSwaggerTemplate loads the Swagger JSON from the file
func LoadSwaggerTemplate(filePath string) (string, error) {
	fileContent, err := os.ReadFile(filePath)
	if err != nil {
		return "", fmt.Errorf("could not read the swagger.json file: %v", err)
	}
	return string(fileContent), nil
}

func init() {
	jsonFilePath := "docs/swagger.json"
	swaggerContent, err := LoadSwaggerTemplate(jsonFilePath)
	if err != nil {
		log.Fatalf("Error loading swagger.json: %v", err)
	}

	SwaggerInfo.SwaggerTemplate = swaggerContent

	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
